### ISSUE TITLE
after copying some snippet from /snippets route its getting redirect to snippets  detail page 

### ISSUE THREAD

**Issue by Vivek7038** [notsoocool/codecache#22]
**Describe the bug**

When we click on copy icon of any snippet in our snippets listing page we are getting redirected to that particular snippet details page , 

**To Reproduce**
1. Go to https://www.codecache.tech/snippets
2. Click on copy icon of any snippet 
3. now you are redirected to snippet detail page after getting copied 

**Expected behavior**
we should only be able to copy on clicking copy icon 
**Screenshots**
![Untitled](https://github.com/user-attachments/assets/45f3c34d-60d7-431d-993a-bab70778f996)

**Comment by Vivek7038** [comment]
Hey @notsoocool  Can  you add it under gssoc-ext and also the level and assign me

**Comment by notsoocool** [comment]
Hi @Vivek7038 ,

Thank you for reporting this bug!

You can go ahead and work on this issue. The expected behavior is that clicking the copy icon should only trigger the copy action without redirecting to the snippet details page.

Let me know if you have any questions while working on it, and feel free to reach out if you need any clarification!

**Comment by Vivek7038** [comment]
@notsoocool The issue is fixed, and I have raised a PR. Please review it at #24 .

can you review merge it .

**Comment by notsoocool** [comment]
Looking forward to more awesome contributions from you!
