### ISSUE TITLE
Make the size of box where code snippet is added change dynamically instead of manual resizing

### ISSUE THREAD

**Issue by ZayedShahcode** [notsoocool/codecache#33]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I am entering many lines of code and the code editor doesn't resize and then I will have to manually resize it using a small resize button of bottom left corner. I want to solve this problem by adding this feature.

**Describe the solution you'd like**
We give a minimum height to the code box. Whenever the no of lines increases and the box becomes scrollable we increase the height of box to scrollable height. Using this we can eliminate the resize button which doesn't look good UI/UX wise.

**Describe alternatives you've considered**
I have mentioned the alternative above

**Additional context**
![image](https://github.com/user-attachments/assets/79751bf9-1c0e-4fe3-b524-80ce092be37e)

**Comment by notsoocool** [comment]
Hi @ZayedShahcode,
Thanks for the suggestion! Improving the code box's usability is a great idea. I like the approach of increasing the height dynamically as more lines of code are entered, and making the box scrollable instead of relying on the resize button would definitely enhance the UX. I’ll look into implementing this. Stay tuned for updates, and feel free to share any other ideas you might have!
